### ISSUE TITLE
undefined method tag

### ISSUE THREAD

**Issue by sipani909** [bernardoamc/minitag#14]
I added the gem to my project and defined the tag as 

```
tag 'trial'
  define_method "test_1_traffic"
```

in my `test.rb` file. However I get the error

```
undefined method `tag' for Traffic:Class (NoMethodError)
```

**Comment by sipani909** [comment]
Same error for the other method as well
```
undefined method `tag_namespace' for Traffic:Class (NoMethodError)
```

**Comment by bernardoamc** [comment]
Hello 👋 

You need to add tags to test classes, apparently you are adding those to a normal class in your system called `Traffic`. Let me know if this helps.

**Comment by sipani909** [comment]
```
class Traffic < Minitest::Test
  include MsTestLibrary
```

is what my test class is defined as.

**Comment by bernardoamc** [comment]
I feel this is a naming error or the gem is not being required.

What happens if you rename your class to `TrafficTest` and your file name to `traffic_test.rb` ?

**Comment by sipani909** [comment]
Same as before
```
Traceback (most recent call last):
        1: from ./tests/nightly_rb/traffic/traffic_test.rb:8:in `<main>'
./tests/nightly_rb/traffic/traffic_test.rb:28:in `<class:TrafficTest>': undefined method `tag' for TrafficTest:Class (NoMethodError)
```

I do have the gem added as
```
require 'minitag'
```

**Comment by sipani909** [comment]
If I prepend the module manually in my test file as 

```
require 'minitag'
MerakiTestMS.singleton_class.prepend(Minitag::MinitestTag)
class TrafficTest < MerakiTestMS
.
.
.
```

I do not see the exception anymore but then the tags are not picked up. The tests still run regardless of what tag I specify

**Comment by bernardoamc** [comment]
It's really challenging to debug based on only these messages, do you have a public repository where I could take a look on things?
