### ISSUE TITLE
Ruby 2.5 support

### ISSUE THREAD

**Issue by kyrofa** [bernardoamc/minitag#15]
This is a nicely done plugin! I actually wrote my own far simpler version before finding it, but I'd rather use yours. However, the codebase I'm trying to tag is using Ruby 2.5 (yes yes I know-- I'm tagging these tests so I can slowly update this massive codebase off of such ancient things).

This gem is not compatible with Ruby 2.5. Would you be open to PRs that made it so? I of course understand if that's just too old for you to care about.

**Comment by kyrofa** [comment]
Decided to go for it-- only one small tweak, after all. See #16.

**Comment by bernardoamc** [comment]
Let's go with it! No reason to not do it if can help you, we have all been in this situation. 😄
