### ISSUE TITLE
Skip tests instead of hiding them

### ISSUE THREAD

**Issue by kyrofa** [bernardoamc/minitag#17]
One of the issues with tagging test suites is that it's easy to lose track of the tests you're excluding when running filtered. I've dealt with that in my own plugin by actually _skipping_ excluded tests instead of hiding them entirely via `runnable_methods`. This is untested, but I think for minitag, that would probably look something like:

```ruby
Minitest::Test.singleton_class.prepend(Module.new do
  def run_one_method(klass, method_name, reporter)
    return super if Minitag.context.no_filters? || Minitag.context.match?(namespace: to_s, name: method_name)

    # Skip this test
    test = klass.new(method_name)
    test.time = 0
    skip = Skip.new('This test did not match filters')
    source = test.method(method_name).source_location
    skip.set_backtrace(["#{source[0]}:#{source[1]}"])
    test.failures << skip
    reporter.prerecord(self, method_name)
    reporter.record(Minitest::Result.from(test))
  end
end)
```

How would you feel about a new CLI flag that makes this behavior opt-in?

**Comment by bernardoamc** [comment]
Happy to incorporate the new option. It will be pretty useful for development while still being quiet in CI for example. 👍
